---
apiVersion: v1
kind: Service
metadata:
  name: oncall-prober-service
  namespace: st-ab5-statsenko
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9081"
    prometheus.io/path: /metrics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: oncall-prober
  ports:
    - name: metrics
      protocol: TCP
      port: 9081
      targetPort: 9081