---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncall-sla-calculator
  namespace: st-ab5-statsenko
  labels:
    app.kubernetes.io/name: oncall-sla-calculator
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oncall-sla-calculator
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oncall-sla-calculator
        app.kubernetes.io/component: web
      annotations:
        sage/group: "ab5_statsenko"
    spec:
      containers:
        - name: oncall-sla-calculator
          image: stacenko763/oncall-sla-calculator
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9081
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9082
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9082
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /metrics
              port: 9082
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: SAGE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: oncall-sla-calculator-configmap
                  key: SAGE_API_URL
            - name: SCRAPE_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: oncall-sla-calculator-configmap
                  key: SCRAPE_INTERVAL
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: oncall-sla-calculator-configmap
                  key: LOG_LEVEL
            - name: METRICS_PORT
              valueFrom:
                configMapKeyRef:
                  name: oncall-sla-calculator-configmap
                  key: METRICS_PORT
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: oncall-sla-calculator-configmap
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: oncall-sla-calculator-configmap
                  key: MYSQL_PORT
            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: oncall-sla-calculator-configmap
                  key: MYSQL_DB_NAME
            - name: SUCCESS_REMOVE_TEAM_PERCENT_SLA
              valueFrom:
                configMapKeyRef:
                  name: oncall-sla-calculator-configmap
                  key: SUCCESS_REMOVE_TEAM_PERCENT_SLA
            - name: P98_CREATION_TEAM_DURATION_MILLIS_SLA
              valueFrom:
                configMapKeyRef:
                  name: oncall-sla-calculator-configmap
                  key: P98_CREATION_TEAM_DURATION_MILLIS_SLA
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: oncall-sla-calculator-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oncall-sla-calculator-secret
                  key: MYSQL_PASSWORD
            - name: SAGE_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: oncall-sla-calculator-secret
                  key: SAGE_AUTH_TOKEN