---
apiVersion: v1
kind: Secret
metadata:
  name: oncall-sla-calculator-secret
type: Opaque
data:
  MYSQL_USER: cm9vdA==
  MYSQL_PASSWORD: MTIzNA==
  SAGE_AUTH_TOKEN: QmVhcmVyIGV5SnJhV1FpT2lJMlJFRkZSRVE1UTBNNVJVSXhNRGN5UVVWRFFURTRRemcxUmpNd05FUkZSRGRHTUVFeU5Ea3hSRVJEUlRZeU5EazVSamxEUlRrelJqbEVPRUpFT0RJMUlpd2lkSGx3SWpvaVNsZFVJaXdpWVd4bklqb2lVbE15TlRZaWZRLmV5SnBjM01pT2lKdFlXNTFiQ0lzSW1WNGNDSTZOREV3TWpRME5EZ3dNQ3dpYVdGMElqb3hOell5TWpneU56TTVMQ0puY205MWNDSTZXeUp6WVdkbFgyRmlOVjl6ZEdGMGMyVnVhMjhpWFN3aWRYQnVJam9pWVdJMVgzTjBZWFJ6Wlc1cmIwQnJaWGxqYkc5aGF5NXNiMk5oYkdodmMzUWlMQ0p3WlhKdGFYTnphVzl1Y3lJNlcxMHNJbU5zYVdWdWRFbGtJam9pWVdJMVgzTjBZWFJ6Wlc1cmJ5SXNJbXAwYVNJNklqVmtNbUk1TURJeExUVmlaR0V0TkRjek1TMDVNVGRtTFRGa056UXdZMlUwWWpnek5DSjkuTk5wWVFzUmc2SEktNDNQZnowak1kT1djY0FTREt5ZEZRRGZSWHhlcExSYzlXZURjbEZZa0N5SUJYSUdOLWN6YXo3X0d6XzJWS3pLVU9QR3JqZ3o2RVRfZUN2X0JkcUJycm04b21xbFZUSzR6RDhlYk82Y09Ha1hUcWVnYlZFck5iNXE4X05tYk9TUm5jVENYX21BNXRJRkx4bkVOX0Fva245bGtQekVTeTVxelI2ZTVHbk5WSGRaRm5KTk9HWlppNGQwMHFiOTJKU1diRE9zc2FfaWlYNGY5LVh4cXFHNlBUakYtejVyRjl4RU5vXzd5Q1FRb09YdVRvcFg1QWlNS3dobUlfd1Q2YmttYXNtVVBiWnprbm1NNWk3MVNFbHF2U0NRXzI0YW9TalBLMUFCUGd2UE1tNVdOMGJMZEw2b3Q1UG5SX0VIREQ2VkdmZURDNk1OSDlR
