---
apiVersion: v1
kind: Service
metadata:
  name: oncall-sla-calculator-service
  namespace: st-ab5-statsenko
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9082"
    prometheus.io/path: /metrics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: oncall-sla-calculator
  ports:
    - name: metrics
      protocol: TCP
      port: 9082
      targetPort: 9082