---
apiVersion: v1
kind: Service
metadata:
  name: oncall-mysql
  namespace: st-ab5-statsenko
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9104"
    prometheus.io/path: /metrics
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
    - name: mysql-exporter
      protocol: TCP
      port: 9104
  clusterIP: None
  selector:
    app: mysql